image: Visual Studio 2013

configuration:
  - Release

install:
  - SET TYPE=%CONFIGURATION%
  - SET DEVSPACE=%APPVEYOR_BUILD_FOLDER%\..

# dcmtk & zlib
  - cd %DEVSPACE%
  - ps: |
      Invoke-WebRequest http://draconpern-buildcache.s3.amazonaws.com/dcmtk-win.7z -Outfile "dcmtk-win.7z"
  - 7z x -y dcmtk-win.7z

#fmjpeg2koj & openjpeg
  - cd %DEVSPACE%
  - ps: |
      Invoke-WebRequest http://draconpern-buildcache.s3.amazonaws.com/fmjpeg2koj-win.7z -Outfile "fmjpeg2koj-win.7z"
  - 7z x -y fmjpeg2koj-win.7z

#wxWidgets
  - cd %DEVSPACE%
  - ps: |
      Invoke-WebRequest http://draconpern-buildcache.s3.amazonaws.com/wxWidgets-win.7z -Outfile "wxWidgets-win.7z"
  - 7z x -y wxWidgets-win.7z
  - set WXWIN=%DEVSPACE%\wxWidgets

#boost
  - cd C:\Libraries\boost_1_60_0
  - call bootstrap
  - SET BOOST_MODULES=--with-atomic --with-thread --with-filesystem --with-system stage --with-date_time --with-regex --with-locale
  - IF "%TYPE%" == "Release" b2 toolset=msvc-11.0 runtime-link=static define=_BIND_TO_CURRENT_VCLIBS_VERSION=1 -j 4 %BOOST_MODULES% stage release
  - IF "%TYPE%" == "Debug"   b2 toolset=msvc-11.0 runtime-link=static define=_BIND_TO_CURRENT_VCLIBS_VERSION=1 -j 4 %BOOST_MODULES% stage debug

before_build:
  - cd %APPVEYOR_BUILD_FOLDER% && mkdir build-%TYPE% && cd build-%TYPE%
  - cmake .. -G "Visual Studio 11" -DwxWidgets_ROOT_DIR=%WXWIN% -DBOOST_ROOT=C:\Libraries\boost_1_60_0 -DDCMTK_DIR=%DEVSPACE%\dcmtk\%TYPE% -DZLIB_ROOT=%DEVSPACE%\zlib\%TYPE% -DFMJPEG2K=%DEVSPACE%\fmjpeg2koj\%TYPE% -DOPENJPEG=%DEVSPACE%\openjpeg\%TYPE%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build-%TYPE%
  - msbuild /P:Configuration=%TYPE% ALL_BUILD.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - 7z a %APPVEYOR_BUILD_FOLDER%\dovo.7z %APPVEYOR_BUILD_FOLDER%\build-%TYPE%\%TYPE%\dovo.exe

artifacts:
  - path: dovo.7z
    name: dovo

deploy:
  provider: S3
  access_key_id:
    secure: ocfx3RWVSyFaLRBBJXRLrvwqFGoftzrWzqUWrx20/bc=
  secret_access_key:
    secure: cVrRAHZDL4OZaPmgpH2RAa6yKD1ckjrMvtL/RozVMTTxiMWe5+3BKGrWv7RzNQLK
  bucket: draconpern-buildcache
  set_public: true
  folder:
  artifact: dovo