image: Visual Studio 2019

configuration:
  - Release

install:
  - SET TYPE=%CONFIGURATION%
  - SET DEVSPACE=%APPVEYOR_BUILD_FOLDER%

build_script:
  - build.bat

artifacts:
  - path: dovo.msi
    name: dovo