#ifndef __dovo_sendStatus__
#define __dovo_sendStatus__

/**
@file
Subclass of sendStatus, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include
#include "engine.h"
#include <wx/timer.h>

/** Implementing sendStatus */
class dovo_sendStatus : public sendStatus
{
	protected:
		// Handlers for sendStatus events.
		void OnStop( wxCommandEvent& event );
	public:
		/** Constructor */
		dovo_sendStatus( wxWindow* parent );
	//// end generated class members
		
		~dovo_sendStatus();
		wxTimer timer;
		void OnTimer( wxTimerEvent& event );
		DICOMFileScanner *m_sender;


};

#endif // __dovo_sendStatus__
