#ifndef __dovo_mainFrame__
#define __dovo_mainFrame__

/**
@file
Subclass of mainFrame, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

#include <wx/dirdlg.h>
#include <wx/config.h>
#include "dovo_destination.h"

/** Implementing mainFrame */
class dovo_mainFrame : public mainFrame
{
	protected:
		// Handlers for mainFrame events.
		void OnBrowse( wxCommandEvent& event );
		void OnDestinationEdit( wxCommandEvent& event );
	public:
		/** Constructor */
		dovo_mainFrame( wxWindow* parent );
	//// end generated class members

		~dovo_mainFrame();
		void SetDestinations();
		std::vector<DestinationEntry> destinations, policyDestinations;
};

#endif // __dovo_mainFrame__
