#ifndef __dovo_mainFrame__
#define __dovo_mainFrame__

/**
@file
Subclass of mainFrame, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

#include <boost/lexical_cast.hpp>
#include <wx/dirdlg.h>
#include <wx/config.h>
#include "dovo_destination.h"
#include "dovo_about.h"
#include "dovo_searchStatus.h"
#include "engine.h"

/** Implementing mainFrame */
class dovo_mainFrame : public mainFrame
{
	protected:
		// Handlers for mainFrame events.
		void OnBrowse( wxCommandEvent& event );
		void OnDestinationEdit( wxCommandEvent& event );
		void OnUpdate( wxCommandEvent& event );
		void OnSend( wxCommandEvent& event );
		void OnAbout( wxCommandEvent& event );
		void OnExit( wxCommandEvent& event );
	public:
		/** Constructor */
		dovo_mainFrame( wxWindow* parent );
	//// end generated class members

		~dovo_mainFrame();
		void FillDestinationList();
		

		engine m_engine;
};

#endif // __dovo_mainFrame__
