#ifndef __dovo_destination__
#define __dovo_destination__

/**
@file
Subclass of destination, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include
#include <vector>
#include "destinationentry.h"

/** Implementing destination */
class dovo_destination : public destination
{
	public:
		/** Constructor */
		dovo_destination( wxWindow* parent );
	//// end generated class members

		std::vector<DestinationEntry> destinations;
	
};

#endif // __dovo_destination__
