#ifndef __dovo_changePatientInfo__
#define __dovo_changePatientInfo__

/**
@file
Subclass of changePatientInfo, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

/** Implementing changePatientInfo */
class dovo_changePatientInfo : public changePatientInfo
{
	public:
		/** Constructor */
		dovo_changePatientInfo( wxWindow* parent );
	//// end generated class members
	
};

#endif // __dovo_changePatientInfo__
