#ifndef __dovo_about__
#define __dovo_about__

/**
@file
Subclass of about, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

/** Implementing about */
class dovo_about : public about
{
	public:
		/** Constructor */
		dovo_about( wxWindow* parent );
	//// end generated class members



};

#endif // __dovo_about__
