#ifndef __dovo_searchStatus__
#define __dovo_searchStatus__

/**
@file
Subclass of searchStatus, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

/** Implementing searchStatus */
class dovo_searchStatus : public searchStatus
{
	public:
		/** Constructor */
		dovo_searchStatus( wxWindow* parent );
	//// end generated class members


};

#endif // __dovo_searchStatus__
